mysql:
  enabled: false
  hostname: 'localhost'
  port: 3306
  username: "root"
  password: ""
  database: "MyDatabase"
  playerstable: "PlayerTable"
settings:
  #ProtocolLib is required !
  vanish: false

  #Locations A and B that define the cube of the area.
  investment-zone: "world:0:0:0;world:0:0:0"

  #Allow or not the refund
  refund-enable: true
  #Define the percentage of money that the player recovers when he gives up his investment.
  refund-percentage: 50
  #Commands executed when the player finish his investment.
  commands-when-player-finish-investment:
    - "give %player% diamond 1"

  #Enable to activate the time limit that the player can invest per day.
  limit-investment-time: false
  #Define time limit that the player can invest per day.
  limit-investment-time-in-second: 36000
  # Define how many player with the same ip can invest
  max-account-with-same-ip-in-investment: 3
  # Allows to format numbers
  # e.g (1 000 000 = 1M)
  money-formatted: true
  progress-bar:
    size: 50
    char: "|"
    progress-color: "&a"
    remaining-progress-color: "&7"
  afk:
    afk-teleport-location: "world:0:0:0"
    # Teleport the player to the investment zone
    # when he becomes AFK.
    teleport-when-afk: false
    #Teleports the player to his original location from
    # when he was teleported to the investment area.
    teleport-back-location: false
    # Prevents a player from being kicked when
    # he becomes afk in the area.
    anti-kick-player: true
